### ISSUE TITLE
您好，我申请了数据集的访问权限，麻烦您通过下

### ISSUE THREAD

**Issue by zzidlezz** [FutureTwT/HMAH#1]

**Comment by FutureTwT** [comment]
十分感谢您对本工作的关注，请您重新发一下申请

**Comment by FutureTwT** [comment]
NUSWIDE 参考 nus-wide-tc21-iall.mat 
Flickr 参考 FLICKR-25K.mat 
https://github.com/jiangqy/DCMH-CVPR2017/tree/master/DCMH_tensorflow/DCMH_tensorflow

**Comment by zzidlezz** [comment]
您好，我重发了申请




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FutureTwT/HMAH"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月8日(星期三) 上午9:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FutureTwT/HMAH] 您好，我申请了数据集的访问权限，麻烦您通过下 (Issue #1)





 
十分感谢您对本工作的关注，请您重新发一下申请

**Comment by zzidlezz** [comment]
您好请教您个问题，就是比如我用MIRFLICKR这个数据集，然后每个bit位数跑100次，10次作为一次测试，比如16bit是在20个epoch时map值最高，32bit是在40，其他两位是在别的epoch，那么我可以直接选取他们各自的最好结果吗，还是说不同位数也要固定到一个epoch，比如说都是50次




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FutureTwT/HMAH"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月8日(星期三) 上午9:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FutureTwT/HMAH] 您好，我申请了数据集的访问权限，麻烦您通过下 (Issue #1)





 
NUSWIDE 参考 nus-wide-tc21-iall.mat
 Flickr 参考 FLICKR-25K.mat
 https://github.com/jiangqy/DCMH-CVPR2017/tree/master/DCMH_tensorflow/DCMH_tensorflow
